package main

const (
	DPL_LANG_BULGARIAN            = "BG"
	DPL_LANG_CZECH                = "CS"
	DPL_LANG_DANISH               = "DA"
	DPL_LANG_GERMAN               = "DE"
	DPL_LANG_GREEK                = "EL"
	DPL_LANG_ENGLISH              = "EN"
	DPL_LANG_ENGLISH_BRITISH      = "EN-GB"
	DPL_LANG_ENGLISH_AMERICAN     = "EN-US"
	DPL_LANG_SPANISH              = "ES"
	DPL_LANG_ESTONIAN             = "ET"
	DPL_LANG_FINNISH              = "FI"
	DPL_LANG_FRENCH               = "FR"
	DPL_LANG_HUNGARIAN            = "HU"
	DPL_LANG_INDONESIAN           = "ID"
	DPL_LANG_ITALIAN              = "IT"
	DPL_LANG_JAPANESE             = "JA"
	DPL_LANG_KOREAN               = "KO"
	DPL_LANG_LITHUANIAN           = "LT"
	DPL_LANG_LATVIAN              = "LV"
	DPL_LANG_NORWEGIAN            = "NB"
	DPL_LANG_DUTCH                = "NL"
	DPL_LANG_POLISH               = "PL"
	DPL_LANG_PORTUGUESE_BRAZILIAN = "PT-BR"
	DPL_LANG_PORTUGUESE_EUROPEAN  = "PT-PT"
	DPL_LANG_ROMANIAN             = "RO"
	DPL_LANG_RUSSIAN              = "RU"
	DPL_LANG_SLOVAK               = "SK"
	DPL_LANG_SLOVENIAN            = "SL"
	DPL_LANG_SWEDISH              = "SV"
	DPL_LANG_TURKISH              = "TR"
	DPL_LANG_UKRAINIAN            = "UK"
	DPL_LANG_CHINESE_SIMPLIFIED   = "ZH"
)
